### ISSUE TITLE
transfer by eosjs

### ISSUE THREAD

**Issue by yankunsam** [EOSIO/eosjs#104]
(node:15091) UnhandledPromiseRejectionWarning: ReferenceError: headers is not defined
    at transactionHeaders (/home/sam/eosapi/test.js:9:29)
    at transaction (/home/sam/eosapi/node_modules/eosjs/lib/write-api.js:591:5)
    at _callee$ (/home/sam/eosapi/node_modules/eosjs/lib/write-api.js:294:48)
    at tryCatch (/home/sam/eosapi/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/sam/eosapi/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/sam/eosapi/node_modules/regenerator-runtime/runtime.js:117:21)
    at tryCatch (/home/sam/eosapi/node_modules/regenerator-runtime/runtime.js:65:40)
    at invoke (/home/sam/eosapi/node_modules/regenerator-runtime/runtime.js:155:20)
    at /home/sam/eosapi/node_modules/regenerator-runtime/runtime.js:165:13
    at <anonymous>
(node:15091) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15091) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jcalfee** [comment]
You must be missing network.createTransaction:
```js
    const headers = config.transactionHeaders ?
      config.transactionHeaders :
      network.createTransaction

    headers(options.expireInSeconds, checkError(callback, async function(rawTx) {
```
This has not come up as an issue before.  How are you configuring Eos?

**Comment by yankunsam** [comment]
I add "broadcast: true," to config, and now it works. Thanks
