### ISSUE TITLE
Error when sending a new account transaction. 

### ISSUE THREAD

**Issue by gravitt8460** [EOSIO/eosjs#130]
I am using Dawn 4.2.  When I submit a new account transaction, I get an error about authorization for the eosio account. I submit this transaction: 

```
eos.transaction(tr => {
  tr.newaccount({
    creator: "eosio",
    name: "acct1",
    owner: pubkey,
    active: pubkey
  });
});
```

I get this response.  I do not have a problem when a call cleos directly. I tried adding an authorization to the transaction but it did not allow that syntax.

```
api error => { message: 'transaction declares authority \'{"actor":"eosio","permission":"active"}\', but does not have signatures for it under a provided delay of 0 ms',
  file: 'authorization_manager.cpp',
  line_number: 405,
  method: 'check_authorization' } http://127.0.0.1:8888/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-05-28T13:56:08","ref_block_num":52,"ref_block_prefix":292376965,"net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"newaccount","authorization":[{"actor":"eosio","permission":"active"}],"data":"0000000000ea3055000000008090113201000000010003675ee3bd2f2421b9f66e501265516d78b5029c67375262b070025ec00ca7262a0100000001000000010003675ee3bd2f2421b9f66e501265516d78b5029c67375262b070025ec00ca7262a01000000"}],"transaction_extensions":[]},"signatures":["SIG_K1_K8uzyz3iVXEAEHP3Ko3TqmW8kt3ibqgpSs1Q2CyVCUDnqjoQhxgmTBRZeY7UVqd6JiRTiigp8A5kPYmTwZiPGErssyP3fP"]}
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}
    at /home/max/dev/eosdev/eosride/app/node_modules/eosjs-api/lib/apigen.js:115:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7) status: 500, statusText: 'Internal Server Error' }
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}
    at /home/max/dev/eosdev/eosride/app/node_modules/eosjs-api/lib/apigen.js:115:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7) status: 500, statusText: 'Internal Server Error' }
[push_transaction error] '{"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}', transaction '780a0c5b340085516d1100000000010000000000ea305500409e9a2264b89a010000000000ea305500000000a8ed3232660000000000ea3055000000008090113201000000010003675ee3bd2f2421b9f66e501265516d78b5029c67375262b070025ec00ca7262a0100000001000000010003675ee3bd2f2421b9f66e501265516d78b5029c67375262b070025ec00ca7262a0100000000'
{"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}
(node:23213) UnhandledPromiseRejectionWarning: {"code":500,"message":"Internal Service Error","error":{"code":3090003,"name":"unsatisfied_authorization","what":"provided keys, permissions, and delays do not satisfy declared authorizations","details":[{"message":"transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it under a provided delay of 0 ms","file":"authorization_manager.cpp","line_number":405,"method":"check_authorization"}]}}
(node:23213) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23213) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by sss-CRS-sss** [comment]
write here your connection settings eos obj

**Comment by gravitt8460** [comment]
How do I access that object? Here's how I'm setting the object up: 

```
Eos = require("eosjs"); // Eos = require('./src')
binaryen = require("binaryen");

keyProvider = "5JhhMGNPsuU42XXjZ57FcDKvbb7KLrehN65tdTQFrH51uruZLHi";
pubkey = "EOS7ckzf4BMgxjgNSYV22rtTXga8R9Z4XWVhYp8TBgnBi2cErJ2hn";

eos = Eos.Localnet({ keyProvider, binaryen });
```

**Comment by sss-CRS-sss** [comment]
Is the same secret key in your local wallet (keosd)? What version of eosjs are you using? In the previous version of eosjs + dawn4.2 I also received this error, but I updated  eosjs and this solved issue

**Comment by sim31** [comment]
I have the same issue on eosjs@13.0.0. It's likely related to: #131

**Comment by jcalfee** [comment]
It could be reated to #131.. try with the chain ID .. Eosjs v13 comes with a chain ID from the dawn 4.2 branch in github.  The community testnest will all very likely use a different chainId.
```js
const chainID = 'a628a5a6123d6ed60242560f23354c557f4a02826e223bb38aad79ddeb9afbca'
eos = Eos.Localnet({ keyProvider, binaryen })
```

**Comment by jcalfee** [comment]
Re-test or close..

**Comment by gravitt8460** [comment]
I will update and re-test this upcoming week. I can close for now and re-open if it occurs again.
