### ISSUE TITLE
error handling: no error is returned in case of error

### ISSUE THREAD

**Issue by robertkowalski** [EOSIO/eosjs#145]
it seems very often nothing happens / is returned from the error callback:

```js
    const account_name = 'user'
    const pos = 0
    const offset = 10

    eos.getActions({
      account_name, pos, offset
    }, (err, res) => {
      if (err) return cb(err)  // expected to be called

      return cb(null, res)
    })

```
Assumption: a promise / the promises used internally missing a `catch` handler, that is passing the error to the callback based API. This appears in the global node process log:

```
(node:28736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
api error => { message: 'Invalid cast from type \'object_type\' to string',
  file: 'variant.cpp',
  line_number: 565,
  method: 'get_string' } http://127.0.0.1:8888/v1/history/get_actions {"account_name":{"account_name":"user","pos":0,"offset":10}}
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":7,"name":"bad_cast_exception","what":"Bad Cast","details":[{"message":"Invalid cast from type 'object_type' to string","file":"variant.cpp","line_number":565,"method":"get_string"}]}}
    at /Users/robert/bitfinex/bfx-coin-eos-js/node_modules/eosjs-api/lib/apigen.js:115:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) status: 500, statusText: 'Internal Server Error' }
```

**Why do we need this?**

Given we want to provide the error in a request / response context we can't rely on the global "uncaughtPromiseException" handler.

**Comment by jcalfee** [comment]
published eosjs@13.0.1

**Comment by jcalfee** [comment]
I need to see your example.  It is working in this case:
```js
> eos.transfer('noacct', 'acct', '1 SYS', 'memo', (err, res)=> console.error('ERROR', err))
undefined
> api error => { message: 'action\'s code account \'eosio.token\' does not exist',
  file: 'controller.cpp',
  line_number: 1420,
  ...

ERROR {"code":500,"message":"Internal Service Error","error":{"code":3040000,"name":"transaction_exception","what":"transaction exception","details":[{"message":"action's code account 'eosio.token' does not exist","file":"controller.cpp","line_number":1420,"method":"validate_referenced_accounts"}]}}
```

**Comment by jcalfee** [comment]
Also works for a read-only api:
```js
> eos.getActions('eosio', 'a', 0, (err, res)=> {console.error('ERROR', err); console.log('RES', res)})
undefined
> api error => { message: 'Couldn\'t parse int64_t',
  ...
ERROR { Error: {"code":500,"message":"Internal Service Error","error":{"code":4,"name":"parse_error_exception","what":"Parse Error","details":[{"message":"Couldn't parse int64_t","file":"string.cpp","line_number":100,"method":"to_int64"}]}}
    at /home/jcalfee/eosjs/eosjs/node_modules/eosjs-api/lib/apigen.js:115:23
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) status: 500, statusText: 'Internal Server Error' }
RES undefined
```

**Comment by ycryptx** [comment]
@jcalfee hey james.

I get this internal error message:
`{"code":500,"message":"Internal Service Error","error":{"code":3050003,"name":"eosio_assert_message_exception","what":"eosio_assert_message assertion failure","details":[{"message":"assertion failure with message: Create() can only be called once","file":"wasm_interface.cpp","line_number":930,"method":"eosio_assert"},{"message":"","file":"apply_context.cpp","line_number":60,"method":"exec_one"}]}}
(node:12004) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'data' of undefined`

I have this assert statement in my contract function 
`    eosio_assert(itr_meta->created != 1, "Create() can only be called once");
`

and in my javascript I call:
```
  eos.transaction({
  actions: [
    {
      account: data.cid,
      name: 'create',
      authorization: [{
        actor: data.cid,
        permission: 'active'
      }],
      data: {
        username : data.username,
      }
      }
    ]
  })  .then(rules => {res.status(200).send({message: "Repo rules were set successfully", rules})})
  .catch(err => {
    console.log(err.response.data);
    res.status(400).send(err: err.response.data);
  });
```

**Comment by jcalfee** [comment]
You can only `create` an asset once.  After that you need to call `issue` to issue some or all of the asset you just created to another account.  Finally, that last account can call `transfer`..
