### ISSUE TITLE
Eosjs cannot connect to https end point

### ISSUE THREAD

**Issue by mlockett42** [EOSIO/eosjs#150]
Libertyblock have an endpoint running with https. However eosjs cannot connect to it. 

The end point is [https://bp.libertyblock.io:8890](https://bp.libertyblock.io:8890) I can access this in the browser or in curl but eosjs fails

The code I have is

```
var options = {
  httpEndpoint: 'https://bp.libertyblock.io:8890',
  debug: false,
  fetchConfiguration: {},
}

eos = Eos.Localnet(options) // testnet at eos.io

eos.getInfo({}).then(
.....
```

Gives

```
api error =>  https://bp.libertyblock.io:8890/v1/chain/get_info {}
{ FetchError: request to https://bp.libertyblock.io:8890/v1/chain/get_info failed, reason: socket hang up
    at ClientRequest.<anonymous> (/opt/project/eos-voter/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'FetchError',
  message: 'request to https://bp.libertyblock.io:8890/v1/chain/get_info failed, reason: socket hang up',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
{ FetchError: request to https://bp.libertyblock.io:8890/v1/chain/get_info failed, reason: socket hang up
    at ClientRequest.<anonymous> (/opt/project/eos-voter/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'FetchError',
  message: 'request to https://bp.libertyblock.io:8890/v1/chain/get_info failed, reason: socket hang up',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
Error result= { FetchError: request to https://bp.libertyblock.io:8890/v1/chain/get_info failed, reason: socket hang up
    at ClientRequest.<anonymous> (/opt/project/eos-voter/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'FetchError',
  message: 'request to https://bp.libertyblock.io:8890/v1/chain/get_info failed, reason: socket hang up',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
```

**Comment by mlockett42** [comment]
I was using Nodejs version 8, upgrading to version 10 has fixed this problem. Nodejs version is a still valid Long term support release so I feel it should have worked

**Comment by jcalfee** [comment]
Node v8.4.0 under Linux works for me ..
