### ISSUE TITLE
Getting Connection Error 

### ISSUE THREAD

**Issue by tacc716** [EOSIO/eosjs#178]
I'm trying to test EOSioJS but not able to start it getting the below error each time :(

{ FetchError: request to http://127.0.0.1:8888/v1/chain/get_info failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (/root/node_modules/eosjs/node_modules/eosjs-api/node_modules/isomorphic-fetch/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  name: 'FetchError',
  message: 'request to http://127.0.0.1:8888/v1/chain/get_info failed, reason: connect ECONNREFUSED 127.0.0.1:8888',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }

**Comment by jcalfee** [comment]
test with `curl  http://127.0.0.1:8888/v1/chain/get_info`  .. if that works, pass `--access-control-allow-origin=*` to nodeosd on the command line or enable the setting in config.ini..
