### ISSUE TITLE
Contract handling - Invalid character: '_' 

### ISSUE THREAD

**Issue by robertkowalski** [EOSIO/eosjs#21]
Hi James,

with the latest version I still run into issues. Getting an instance of the `exchange` contract works for me, but sending the message does not.

```js
  const options = {
    broadcast: true,
    sign: true,
    scope: [
      "exchange"
    ],
    authorization: [{
      "account": "inita",
      "permission": "active"
    }]
  }

  const msg = {
    "buyer":{ "name": "inita", "number": "1516073924"},
    "at_price":"5000000000000000",
    "expiration":"2018-12-31T23:59:59",
    "quantity": "100",
    "fill_or_kill": "0"
  }

  eos
    .contract('exchange', options)
    .then((contract) => {
      contract.buy(msg)
    })
```

results in:

```
TypeError: Invalid character: '_' message.type = "buy_order" transaction.messages = [{"code":"exchange","type":"buy_order","authorization":[],"data":{"buyer":{"name":"inita","number":"1516073924"},"at_price":"5000000000000000","quantity":"100","expiration":1546300799,"fill_or_kill":"0"}}]
    at charidx (/Users/robert/test/node_modules/eosjs/lib/format.js:61:25)
    at encodeName (/Users/robert/test/node_modules/eosjs/lib/format.js:90:31)
    at Object.appendByteBuffer (/Users/robert/test/node_modules/eosjs/lib/structs.js:97:21)
    at Object.appendByteBuffer (/Users/robert/test/node_modules/fcbuffer/lib/struct.js:103:20)
    at Object.appendByteBuffer (/Users/robert/test/node_modules/fcbuffer/lib/types.js:292:16)
    at Object.appendByteBuffer (/Users/robert/test/node_modules/fcbuffer/lib/struct.js:103:20)
    at toByteBuffer (/Users/robert/test/node_modules/fcbuffer/lib/fcbuffer.js:282:8)
    at Function.toBuffer (/Users/robert/test/node_modules/fcbuffer/lib/fcbuffer.js:269:22)
    at /Users/robert/test/node_modules/eosjs/lib/write-api.js:519:26
    at /Users/robert/test/node_modules/eosjs/lib/write-api.js:660:7
```

does the exchange contract work for you?

**Comment by jcalfee** [comment]
This is an issue and not trivial to fix, I have already looked at it.  I'm at a conference now though and returning to the states on Feb21 so It will probably be after the 21..

**Comment by jcalfee** [comment]
You could perhaps work-around this by renaming the actions (for example, rename "buy_order" to "buy") in the ABI and re-deploying.

And the same for the other actions, rename the type to match the action_name:

```js
  "actions": [{
      "action_name": "buy",
      "type": "buy_order"
    },{
      "action_name": "sell",
      "type": "sell_order"
    },{
      "action_name": "cancelbuy",
      "type": "order_id"
    },{
      "action_name": "cancelsell",
      "type": "order_id"
    }
  ],```

**Comment by robertkowalski** [comment]
hi james,

any updates here?

**Comment by jcalfee** [comment]
Hi Robert .. I'm looking at it now..

**Comment by jcalfee** [comment]
I just pushed eosjs@6.1.7 to npm .. This fixes the reported problem.  I need to figure out how to give myself a balance in the exchange to test further.

**Comment by robertkowalski** [comment]
thanks @jcalfee 

running into another issue now, probably i don't sign the message properly?

```js
const eos = eos.Localnet({
  keyProvider: '5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3'
})

  const options = {
    broadcast: true,
    sign: true,
    scope: [
      "exchange"
    ],
    authorization: [{
      "account": "inita",
      "permission": "active"
    }]
  }

  const msg = {
    "buyer":{ "name": "inita", "number": "1516073924"},
    "at_price":"5000000000000000",
    "expiration":"2018-12-31T23:59:59",
    "quantity": "100",
    "fill_or_kill": 0
  }

  eos
    .contract('exchange', options)
    .then((contract) => {
      contract.buy(msg)
    })
```

```
{ at_price: '100',
  expiration: '2018-12-31T23:59:59',
  quantity: '1',
  fill_or_kill: 1,
  buyer: { name: 'inita', number: 77829758 } }
{ Error: {"code":400,"message":"Bad Request","details":"irrelevant signature included (3030004)\nTransaction bears irrelevant signatures from these keys: [\"EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV\"]\n\n"}
    at /Users/robert/bitfinex/sunbeam/node_modules/eosjs-api/lib/apigen.js:98:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) status: 400, statusText: 'Bad Request' }
[push_transaction error] '{"code":400,"message":"Bad Request","details":"irrelevant signature included (3030004)\nTransaction bears irrelevant signatures from these keys: [\"EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV\"]\n\n"}', digest '54b51e67b9e84fb8965a0000010000008a4dd35057000000000000bc3e002d000000000093dd74c4735d5a000000000080e03779c31100000000000000000064000000000000007fad2a5c00'
{"code":400,"message":"Bad Request","details":"irrelevant signature included (3030004)\nTransaction bears irrelevant signatures from these keys: [\"EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV\"]\n\n"}
(node:81574) UnhandledPromiseRejectionWarning: {"code":400,"message":"Bad Request","details":"irrelevant signature included (3030004)\nTransaction bears irrelevant signatures from these keys: [\"EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV\"]\n\n"}
(node:81574) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:81574) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by robertkowalski** [comment]
ok, i added all the private keys i created for the exchange contract, in an array for the `keyProvider` prop, now running into:

```
Error: missing required keys for {"ref_block_num":46952,"ref_block_prefix":1679695473,"expiration":"2018-02-28T14:19:15","scope":[],"read_scope":[],"messages":[{"code":"exchange","type":"buy","authorization":[],"data":{"buyer":{"name":"inita","number":"1516073924"},"at_price":"5000000000000000","quantity":"100","expiration":"2018-12-31T23:59:59","fill_or_kill":0}}]}
    at /Users/robert/bitfinex/sunbeam/node_modules/eosjs/lib/index.js:220:15
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
Error: missing required keys for {"ref_block_num":46952,"ref_block_prefix":1679695473,"expiration":"2018-02-28T14:19:15","scope":[],"read_scope":[],"messages":[{"code":"exchange","type":"buy","authorization":[],"data":{"buyer":{"name":"inita","number":"1516073924"},"at_price":"5000000000000000","quantity":"100","expiration":"2018-12-31T23:59:59","fill_or_kill":0}}]}
    at /Users/robert/bitfinex/sunbeam/node_modules/eosjs/lib/index.js:220:15
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:81713) UnhandledPromiseRejectionWarning: Error: missing required keys for {"ref_block_num":46952,"ref_block_prefix":1679695473,"expiration":"2018-02-28T14:19:15","scope":[],"read_scope":[],"messages":[{"code":"exchange","type":"buy","authorization":[],"data":{"buyer":{"name":"inita","number":"1516073924"},"at_price":"5000000000000000","quantity":"100","expiration":"2018-12-31T23:59:59","fill_or_kill":0}}]}
    at /Users/robert/bitfinex/sunbeam/node_modules/eosjs/lib/index.js:220:15
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:81713) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:81713) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by chris-allnutt** [comment]
@robertkowalski are you running on Dawn 2.x or the current version in master?  @jcalfee is working on adding support for Dawn 3.x (master).  There are some breaking changes between the 2 versions.  Current EosJS should work with 2.x https://github.com/EOSIO/eos/tree/dawn-2.x

**Comment by robertkowalski** [comment]
aw, ok, retrying with latest master. thanks for the hint!

**Comment by robertkowalski** [comment]
oh, latest master requires at least 100Gig free space...

**Comment by jcalfee** [comment]
eosio/eos master is dawn3 (the eosiod executable) so that is not going to work.. you need the dawn-2 branch (the: eosd executable).

**Comment by chris-allnutt** [comment]
@robertkowalski were you able to get past this issue, or do you have additional details?

**Comment by robertkowalski** [comment]
i still run into the issue reported with eos 2 / eosd

```
Error: missing required keys for {"ref_block_num":46952,"ref_block_prefix":1679695473,"expiration":"2018-02-28T14:19:15","scope":[],"read_scope":[],"messages":[{"code":"exchange","type":"buy","authorization":[],"data":{"buyer":{"name":"inita","number":"1516073924"},"at_price":"5000000000000000","quantity":"100","expiration":"2018-12-31T23:59:59","fill_or_kill":0}}]}
    at /Users/robert/bitfinex/sunbeam/node_modules/eosjs/lib/index.js:220:15
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
Error: missing required keys for {"ref_block_num":46952,"ref_block_prefix":1679695473,"expiration":"2018-02-28T14:19:15","scope":[],"read_scope":[],"messages":[{"code":"exchange","type":"buy","authorization":[],"data":{"buyer":{"name":"inita","number":"1516073924"},"at_price":"5000000000000000","quantity":"100","expiration":"2018-12-31T23:59:59","fill_or_kill":0}}]}
    at /Users/robert/bitfinex/sunbeam/node_modules/eosjs/lib/index.js:220:15
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:81713) UnhandledPromiseRejectionWarning: Error: missing required keys for {"ref_block_num":46952,"ref_block_prefix":1679695473,"expiration":"2018-02-28T14:19:15","scope":[],"read_scope":[],"messages":[{"code":"exchange","type":"buy","authorization":[],"data":{"buyer":{"name":"inita","number":"1516073924"},"at_price":"5000000000000000","quantity":"100","expiration":"2018-12-31T23:59:59","fill_or_kill":0}}]}
    at /Users/robert/bitfinex/sunbeam/node_modules/eosjs/lib/index.js:220:15
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:81713) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:81713) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

@jcalfee how do i sign my request properly?

**Comment by robertkowalski** [comment]
code is still:

```js
const eos = eos.Localnet({
  keyProvider: '5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3',
  // all other keys i created with the exchange tutorial...
})

  const options = {
    broadcast: true,
    sign: true,
    scope: [
      "exchange"
    ],
    authorization: [{
      "account": "inita",
      "permission": "active"
    }]
  }

  const msg = {
    "buyer":{ "name": "inita", "number": "1516073924"},
    "at_price":"5000000000000000",
    "expiration":"2018-12-31T23:59:59",
    "quantity": "100",
    "fill_or_kill": 0
  }

  eos
    .contract('exchange', options)
    .then((contract) => {
      contract.buy(msg)
    })
```

**Comment by jcalfee** [comment]
This key works with a simple transfer from inita?  I did get the signature to verify in my test.  I'll set it up again and run the test again, it is very possible there is another bug.  Signing depends on very precise serialization.  Please stand by..

**Comment by robertkowalski** [comment]
thanks... yes i use it with the keys generated in https://gist.github.com/andriantolie/b94054cb8fe8d356a7783fcd4536510e

**Comment by robertkowalski** [comment]
fixed with help from @jcalfee 

here is the solution:

```js
  const msg = {
    "buyer":{ "name": "inita", "number": "1317073924"},
    "at_price":"5000000000000000",
    "expiration":"2018-12-31T23:59:59",
    "quantity": "100",
    "fill_or_kill": 0
  }

  eos
    .contract('exchange')
    .then((contract) => {
      contract.buy(msg, { scope: 'exchange', authorization: [{account: 'inita', permission: 'active'}] })
    })
```
