### ISSUE TITLE
Action Fails Authorisation

### ISSUE THREAD

**Issue by MitchPierias** [EOSIO/eosjs#218]
I keep getting the following authorisation error when trying to call an action on my test contract.

```
AssertionError {name: "AssertionError", actual: false, expected: true, operator: "==", message: "Invalid public key", …}
```
```
"AssertionError: Invalid public key
    at Object.PublicKey (http://localhost:3000/static/js/bundle.js:18870:9)
    at http://localhost:3000/static/js/bundle.js:20395:38
    at Array.map (<anonymous>)
    at Object._callee$ (http://localhost:3000/static/js/bundle.js:20389:25)
    at tryCatch (http://localhost:3000/static/js/bundle.js:63494:40)
    at Generator.invoke [as _invoke] (http://localhost:3000/static/js/bundle.js:63728:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/bundle.js:63546:21)
    at tryCatch (http://localhost:3000/static/js/bundle.js:63494:40)
    at invoke (http://localhost:3000/static/js/bundle.js:63584:20)
    at http://localhost:3000/static/js/bundle.js:63594:13"
```

Below is the Javascript browser code I'm using to call the action. The `test` account has been created under the wallet signed by the same private key using in the `config`.

```
const config = {
    keyProvider: "PRIVATE_KEY",
    httpEndpoint: 'http://127.0.0.1:8888',
    expireInSeconds: 120,
    broadcast: true,
    debug: false,
    sign: true
}

const eos = EOSJS(config);

eos.contract('test').then(function(testContract) {
    testContract.submit("inita",0,"UNIQUE_SHA_256_HASH", {authorization:"inita"}).then(function(result) {
        console.log(result);
    });
});
```

**Comment by jcalfee** [comment]
Is your ABI is expecting a public key?

You need to add a `return` like this:
```js
eos.contract('test').then(function(testContract) {
    return testContract.submit("inita",0,"UNIQUE_SHA_256_HASH", {authorization:"inita"}).then(function(result) {
        console.log(result);
    });
});
```

**Comment by MitchPierias** [comment]
My ABI doesn't seem to state anything about a public key. But the `return` within the contract callback didn't resolve the problem. Below is my ABI;

```
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-06-23T04:44:13",
  "version": "eosio::abi/1.0",
  "types": [],
  "structs": [{
      "name": "Ticket",
      "base": "",
      "fields": [{
          "name": "id",
          "type": "uint64"
        },{
          "name": "game",
          "type": "uint64"
        },{
          "name": "owner",
          "type": "name"
        },{
          "name": "prediction",
          "type": "checksum256"
        }
      ]
    },{
      "name": "submit",
      "base": "",
      "fields": [{
          "name": "account",
          "type": "name"
        },{
          "name": "game",
          "type": "uint64"
        },{
          "name": "prediction",
          "type": "checksum256"
        }
      ]
    }
  ],
  "actions": [{
      "name": "submit",
      "type": "submit",
      "ricardian_contract": ""
    }
  ],
  "tables": [{
      "name": "tickets",
      "index_type": "i64",
      "key_names": [
        "id"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "Ticket"
    }
  ],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": []
}
```

**Comment by jcalfee** [comment]
If you had a source maps configured in your environment that would make it easier.  

What does this secion of code look like?
```js
at http://localhost:3000/static/js/bundle.js:20395:38
```

Array.map (<anonymous>) must have something other than a public key or a public key in a unexpected format..

**Comment by MitchPierias** [comment]
Not sure how to turn on _source maps_. I did find that my private key contained an additional **PW...** at the beginning of the string. My error's now changed too;

```
POST http://127.0.0.1:8888/v1/chain/push_transaction 500 (Internal Server Error)
(anonymous) @ apigen.js:90
(anonymous) @ write-api.js:728
Promise.then (async)
_callee2$ @ write-api.js:681
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.(anonymous function) @ runtime.js:114
tryCatch @ runtime.js:62
invoke @ runtime.js:152
(anonymous) @ runtime.js:195
callInvokeWithMethodAndArg @ runtime.js:194
enqueue @ runtime.js:217
prototype.(anonymous function) @ runtime.js:114
./node_modules/regenerator-runtime/runtime.js.runtime.async @ runtime.js:241
_callee2 @ write-api.js:642
(anonymous) @ write-api.js:837
(anonymous) @ exported-helpers.js:68
(anonymous) @ exported-helpers.js:78
callback @ process-args.js:65
(anonymous) @ apigen.js:106
Promise.then (async)
(anonymous) @ apigen.js:101
(anonymous) @ exported-helpers.js:51
(anonymous) @ exported-helpers.js:78
callback @ process-args.js:65
(anonymous) @ apigen.js:106
Promise.then (async)
(anonymous) @ apigen.js:101
createTransaction @ exported-helpers.js:48
api.(anonymous function) @ apigen.js:45
transaction @ write-api.js:640
_callee$ @ write-api.js:303
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.(anonymous function) @ runtime.js:114
tryCatch @ runtime.js:62
invoke @ runtime.js:152
(anonymous) @ runtime.js:162
Promise.then (async)
invoke @ runtime.js:161
(anonymous) @ runtime.js:195
callInvokeWithMethodAndArg @ runtime.js:194
enqueue @ runtime.js:217
prototype.(anonymous function) @ runtime.js:114
./node_modules/regenerator-runtime/runtime.js.runtime.async @ runtime.js:241
_callee @ write-api.js:110
(anonymous) @ write-api.js:432
_callee2$ @ WalletActions.js:16
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.(anonymous function) @ runtime.js:114
step @ TransactionReducer.js:21
(anonymous) @ TransactionReducer.js:21
Promise.then (async)
step @ TransactionReducer.js:21
(anonymous) @ TransactionReducer.js:21
(anonymous) @ TransactionReducer.js:21
(anonymous) @ WalletActions.js:16
(anonymous) @ index.js:11
willPurchaseTokens @ Wallet.js:40
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:201
executeDispatch @ react-dom.development.js:466
executeDispatchesInOrder @ react-dom.development.js:488
executeDispatchesAndRelease @ react-dom.development.js:586
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:597
forEachAccumulated @ react-dom.development.js:567
runEventsInBatch @ react-dom.development.js:728
runExtractedEventsInBatch @ react-dom.development.js:737
handleTopLevel @ react-dom.development.js:4201
batchedUpdates @ react-dom.development.js:12537
batchedUpdates @ react-dom.development.js:1939
dispatchEvent @ react-dom.development.js:4282
interactiveUpdates @ react-dom.development.js:12592
interactiveUpdates @ react-dom.development.js:1958
dispatchInteractiveEvent @ react-dom.development.js:4259
```

And the API error;

```
api < error 	 undefined http://127.0.0.1:8888/v1/chain/push_transaction 
{
  "compression":"none",
  "transaction":
    {
      "expiration":"2018-06-27T15:09:20",
      "ref_block_num":52887,
      "ref_block_prefix":2265322052,
      "net_usage_words":0,
      "max_cpu_usage_ms":0,
      "delay_sec":0,
       "context_free_actions":[],
       "actions":[
         {
           "account":"members",
           "name":"deposit",
           "authorization":[{           
              "actor":"mitch",
              "permission":"active"
           }],
           "data":"000000008086b2930400000000000000"
         }
       ],
      "transaction_extensions":[]
    },
    "signatures":["SIG_K1_JuikUhxUQZx7SFQQqUNScKxmjNh4ZstaLCsiZVUoLSWSFBhJz8zZVrV83oEtf1AnGGyZf3j4JByAquFTKYAeTtYpVBwkx3"]
}
```

**Comment by jcalfee** [comment]
That is either your private key or chainId ..

**Comment by MitchPierias** [comment]
Interesting, I've triple checked all of that, I'm just going to completely wipe my chain and keys and start fresh.

**Comment by jcalfee** [comment]
Keep in mind, the cleos wallet creates random keys so you have to backup the entire wallet in addition to the PW{key}..

**Comment by karankurbur** [comment]
@jcalfee 
thanks so much!!! i had no idea that that you had to use the password to view the pkey for the acc.
