### ISSUE TITLE
Error when initialize Eos

### ISSUE THREAD

**Issue by giniz** [EOSIO/eosjs#230]
Hi all,
Today I get error with below lines after run **npm i** again  (yesterday everything worked well with same code):
const eos = Eos({ signProvider });
eos.contract('stock')

Am using eosjs 15.0.3
```
Caught Error Error: [
    "Expecting string in extensions_type.fields.isEmpty",
    "Expecting string in transaction_header.fields.isEmpty",
    "Expecting string in transaction.fields.isEmpty",
    "Expecting string in signed_transaction.fields.isEmpty",
    "Expecting string in field_def.fields.isEmpty",
    "Expecting string in producer_key.fields.isEmpty",
    "Expecting string in producer_schedule.fields.isEmpty",
    "Expecting string in chain_config.fields.isEmpty",
    "Expecting string in type_def.fields.isEmpty",
    "Expecting string in struct_def.fields.isEmpty",
    "Expecting string in clause_pair.fields.isEmpty",
    "Expecting string in error_message.fields.isEmpty",
    "Expecting string in abi_def.fields.isEmpty",
    "Expecting string in table_def.fields.isEmpty",
    "Expecting string in action.fields.isEmpty",
    "Expecting string in action_def.fields.isEmpty",
    "Expecting string in block_header.fields.isEmpty",
    "Expecting string in packed_transaction.fields.isEmpty",
    "Expecting string in nonce.fields.isEmpty",
    "Expecting string in authority.fields.isEmpty",
    "Expecting string in bidname.fields.isEmpty",
    "Expecting string in blockchain_parameters.fields.isEmpty",
    "Expecting string in buyram.fields.isEmpty",
    "Expecting string in buyrambytes.fields.isEmpty",
    "Expecting string in canceldelay.fields.isEmpty",
    "Expecting string in claimrewards.fields.isEmpty",
    "Expecting string in connector.fields.isEmpty",
    "Expecting string in delegatebw.fields.isEmpty",
    "Expecting string in delegated_bandwidth.fields.isEmpty",
    "Expecting string in deleteauth.fields.isEmpty",
    "Expecting string in eosio_global_state.fields.isEmpty",
    "Expecting string in exchange_state.fields.isEmpty",
    "Expecting string in key_weight.fields.isEmpty",
    "Expecting string in linkauth.fields.isEmpty",
    "Expecting string in namebid_info.fields.isEmpty",
    "Expecting string in newaccount.fields.isEmpty",
    "Expecting string in onerror.fields.isEmpty",
    "Expecting string in permission_level.fields.isEmpty",
    "Expecting string in permission_level_weight.fields.isEmpty",
    "Expecting string in producer_info.fields.isEmpty",
    "Expecting string in refund.fields.isEmpty",
    "Expecting string in refund_request.fields.isEmpty",
    "Expecting string in regproducer.fields.isEmpty",
    "Expecting string in regproxy.fields.isEmpty",
    "Expecting string in require_auth.fields.isEmpty",
    "Expecting string in rmvproducer.fields.isEmpty",
    "Expecting string in sellram.fields.isEmpty",
    "Expecting string in set_account_limits.fields.isEmpty",
    "Expecting string in set_global_limits.fields.isEmpty",
    "Expecting string in set_producers.fields.isEmpty",
    "Expecting string in setabi.fields.isEmpty",
    "Expecting string in setcode.fields.isEmpty",
    "Expecting string in setparams.fields.isEmpty",
    "Expecting string in setpriv.fields.isEmpty",
    "Expecting string in setram.fields.isEmpty",
    "Expecting string in total_resources.fields.isEmpty",
    "Expecting string in undelegatebw.fields.isEmpty",
    "Expecting string in unlinkauth.fields.isEmpty",
    "Expecting string in unregprod.fields.isEmpty",
    "Expecting string in updateauth.fields.isEmpty",
    "Expecting string in user_resources.fields.isEmpty",
    "Expecting string in voteproducer.fields.isEmpty",
    "Expecting string in voter_info.fields.isEmpty",
    "Expecting string in wait_weight.fields.isEmpty",
    "Expecting string in account.fields.isEmpty",
    "Expecting string in create.fields.isEmpty",
    "Expecting string in currency_stats.fields.isEmpty",
    "Expecting string in issue.fields.isEmpty",
    "Expecting string in transfer.fields.isEmpty",
    "Expecting object or string under isEmpty, instead got function",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in extensions_type.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in transaction_header.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in transaction.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in signed_transaction.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in field_def.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in producer_key.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in producer_schedule.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in chain_config.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in type_def.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in struct_def.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in clause_pair.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in error_message.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in abi_def.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in table_def.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in action.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in action_def.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in block_header.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in packed_transaction.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in nonce.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in authority.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in bidname.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in blockchain_parameters.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in buyram.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in buyrambytes.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in canceldelay.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in claimrewards.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in connector.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in delegatebw.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in delegated_bandwidth.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in deleteauth.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in eosio_global_state.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in exchange_state.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in key_weight.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in linkauth.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in namebid_info.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in newaccount.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in onerror.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in permission_level.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in permission_level_weight.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in producer_info.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in refund.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in refund_request.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in regproducer.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in regproxy.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in require_auth.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in rmvproducer.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in sellram.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in set_account_limits.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in set_global_limits.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in set_producers.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in setabi.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in setcode.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in setparams.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in setpriv.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in setram.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in total_resources.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in undelegatebw.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in unlinkauth.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in unregprod.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in updateauth.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in user_resources.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in voteproducer.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in voter_info.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in wait_weight.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in account.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in create.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in currency_stats.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in issue.fields.isEmpty",
    "Missing function () {\n  for (var key in this) {\n    if (this.hasOwnProperty(key)) return false;\n  }\n  return true;\n} in transfer.fields.isEmpty"
]
    at module.exports (/home/longnh31/Downloads/workspace/node_modules/eosjs/lib/structs.js:140:11)
    at createEos (/home/longnh31/Downloads/workspace/node_modules/eosjs/lib/index.js:98:18)
    at Eos (/home/longnh31/Downloads/workspace/node_modules/eosjs/lib/index.js:42:10)
    at Function.Localnet (/home/longnh31/Downloads/workspace/node_modules/eosjs/lib/index.js:69:12)
```

**Comment by jcalfee** [comment]
How are you running this command?  Are you getting a deprecated warning from using Eos.Localnet ?

Double check `npm ls eosjs` and `Eos.version`.

**Comment by giniz** [comment]
Sorry, it was my mistake when trying to customize prototype json.
