### ISSUE TITLE
Unable to Create an Account in Mainnet

### ISSUE THREAD

**Issue by jaybkim1** [EOSIO/eosjs#246]
## Source code of test.js

```
var Eos = require('eosjs')

const config = {
    chainId: 'aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906', 
    keyProvider: [ 'MY PRIVATE KEY' ], 
    httpEndpoint: 'https://api.eosnewyork.io:443',
    verbose: false,
    broadcast: true,
    sign: true,
    expireInSeconds: 30
}

// I made sure it is connected to Mainnet
const eos = Eos(config)

async function newAccount() {
  const pubkey = 'EOS8f81TUNiZfUZsgxhaHqSnYKhCsjEPAeoTTaRtc4Af1eh2r62tw'
  const creator = 'g44tsojxguge'
  const name = 'testjaybjayb'
  const owner = pubkey
  const active = pubkey

  const res = await eos.newaccount(creator, name, owner, active);

  const payer = 'g44tsojxguge'
  const receiver = 'testjaybjayb'
  const bytes = 4096

  const res1 = await eos.buyrambytes(payer, receiver, bytes)

  const from = 'g44tsojxguge'
  const stake_net_quantity = '0.0100 EOS'
  const stake_cpu_quantity = '0.0100 EOS'

  const res2 = await eos.delegatebw(from, receiver, stake_net_quantity, stake_cpu_quantity)

  console.log(res);
  console.log(res1);
  console.log(res2);
}

newAccount();
```

### Execute test.js 

$ node test.js

### Error 

```
api < error 	 undefined https://api.eosnewyork.io:443/v1/chain/push_transaction {"compression":"none","transaction":{"expiration":"2018-07-10T06:55:11","ref_block_num":62982,"ref_block_prefix":2633072553,"net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"newaccount","authorization":[{"actor":"g44tsojxguge","permission":"active"}],"data":"a09866fd519c096170bc79c79b97b1ca01000000010003f06e40086b1b3c06a14a6761f032c1d1c6d319fc0ff8390d94bf29ba07d71f730100000001000000010003f06e40086b1b3c06a14a6761f032c1d1c6d319fc0ff8390d94bf29ba07d71f7301000000"}],"transaction_extensions":[]},"signatures":["SIG_K1_K6gjSh6ieJfxkUEneVYpV9Kfp5j62veGGVZoXhAWbpCPACpnqnyizvHnisUaCoMF6CVjacsKMeso75ea3rMm1dRjPPubhS"]}
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":3080001,"name":"ram_usage_exceeded","what":"account using more than allotted RAM usage","details":[]}}
    at /Users/coincube/dev/workspace-crypto/eosjs/node_modules/eosjs-api/lib/apigen.js:95:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) status: 500, statusText: 'Internal Server Error' }
[push_transaction error] '{"code":500,"message":"Internal Service Error","error":{"code":3080001,"name":"ram_usage_exceeded","what":"account using more than allotted RAM usage","details":[]}}', transaction '4f58445b06f6a97ff19c00000000010000000000ea305500409e9a2264b89a01a09866fd519c096100000000a8ed323266a09866fd519c096170bc79c79b97b1ca01000000010003f06e40086b1b3c06a14a6761f032c1d1c6d319fc0ff8390d94bf29ba07d71f730100000001000000010003f06e40086b1b3c06a14a6761f032c1d1c6d319fc0ff8390d94bf29ba07d71f730100000000'
{"code":500,"message":"Internal Service Error","error":{"code":3080001,"name":"ram_usage_exceeded","what":"account using more than allotted RAM usage","details":[]}}
(node:13697) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): {"code":500,"message":"Internal Service Error","error":{"code":3080001,"name":"ram_usage_exceeded","what":"account using more than allotted RAM usage","details":[]}}
(node:13697) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I made sure I have enough EOS and RAM in my account g44tsojxguge.

I also tested to create an account using **cleos*, and it is created well.

Does anyone know why ?

**Comment by jaybkim1** [comment]
I set **verbose** parameter to **true** and only newaccount() triggers,  here is the result.
```

verbose: true, // API activity

async function newAccount() {
    const pubkey = 'EOS8f81TUNiZfUZsgxhaHqSnYKhCsjEPAeoTTaRtc4Af1eh2r62tw'
    const creator = 'g44tsojxguge'
    const name = 'testjaybjayb'
    const owner = pubkey
    const active = pubkey

    console.log(res);
}

newAccount();
```

**Comment by bkawk** [comment]
Same issue as here https://github.com/EOSIO/eosjs/issues/248

**Comment by jcalfee** [comment]
Did you try creating the account and buying ram and bandwidth in the same transaction?
https://github.com/EOSIO/eosjs#new-account

**Comment by jcalfee** [comment]
In addition to running in a single transaction you might need more "bytes" ..
`bytes=3.5 * 1024`

**Comment by jaybkim1** [comment]
@jcalfee @bkawk 
I successfully created an account with below code.

```
function newAccount() {
  return eos.transaction(tr => {
    tr.newaccount({
      creator: '',
      name: '',
      owner: '',
      active: ''
    })
    tr.buyrambytes({
      payer: '',
      receiver: '',
      bytes: 4096
    })
    tr.delegatebw({
      from: '',
      receiver: '',
      stake_net_quantity: '0.0100 EOS',
      stake_cpu_quantity: '0.0100 EOS',
      transfer: 0
    })
  })
}

async function createNew() {
  const res =  await newAccount();
  console.log("res", res)
}
createNew();
```
