### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by deosgames** [EOSIO/eosjs#333]
So we are calling our contract or tables to see updates on like 100ms speed but rarely get this unhandled exception, which can't be caught by normal Try/Catch. Do you think it can be fixed inside of EOS JS?
 It is on heroku/nodejs if helps...

2018-09-08T09:48:24.612900+00:00 app[web.1]:     at /app/node_modules/eosjs-api/lib/apigen.js:112:23
2018-09-08T09:48:24.612902+00:00 app[web.1]:     at <anonymous>
2018-09-08T09:48:24.612906+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:188:7) status: 429, statusText: 'Too Many Requests' }
2018-09-08T09:48:24.615878+00:00 app[web.1]:     at JSON.parse (<anonymous>)
2018-09-08T09:48:24.615875+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token E in JSON at position 0
2018-09-08T09:48:24.615879+00:00 app[web.1]:     at eos.contract.then.then.catch.closeError (/app/app.js:327:27)
2018-09-08T09:48:24.615881+00:00 app[web.1]:     at <anonymous>
2018-09-08T09:48:24.615882+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:188:7)
2018-09-08T09:48:24.616001+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2018-09-08T09:48:24.616102+00:00 app[web.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jcalfee** [comment]
Eosjs is probably handing the exception to you.  It is however easy to miss one.  Make sure your code is awaiting on every function call to eosjs that triggers network activity.  Post some examples if your not sure.  The README should hightlight all the places you need to wait.  It is pure intuition though, the highest level API call that triggers the transaction is the place to look for the exception.
