### ISSUE TITLE
Error: maxLen validation requries a "length" property struct_t.fields abi.structs setcode.code_abi message.data transaction.messages

### ISSUE THREAD

**Issue by luoxianjiao** [EOSIO/eosjs#35]
when run "eos.setcode" , it occurs error as title！
Error: maxLen validation requries a "length" property struct_t.fields abi.structs setcode.code_abi message.data transaction.messages
at validate (/usr/local/eosjs-master/node_modules/fcbuffer/lib/types.js:663:13)
    at Object.fromObject (/usr/local/eosjs-master/node_modules/fcbuffer/lib/types.js:570:7)
    at Object.fromObject (/usr/local/eosjs-master/node_modules/fcbuffer/lib/types.js:234:45)
    at Object.fromObject (/usr/local/eosjs-master/node_modules/fcbuffer/lib/struct.js:144:34)
    at Object.fromObject (/usr/local/eosjs-master/node_modules/fcbuffer/lib/types.js:320:28)
    at Object.fromObject (/usr/local/eosjs-master/node_modules/fcbuffer/lib/struct.js:144:34)
    at Object.fromObject (/usr/local/eosjs-master/node_modules/fcbuffer/lib/struct.js:144:34)
    at message.data.fromObject (/usr/local/eosjs-master/src/structs.js:333:27)
    at Object.fromObject (/usr/local/eosjs-master/node_modules/fcbuffer/lib/struct.js:141:15)
    at Object.fromObject (/usr/local/eosjs-master/node_modules/fcbuffer/lib/types.js:320:28)

**Comment by chris-allnutt** [comment]
@luoxianjiao 

1. Which version of eosjs are you running?  Master or ```@dawn3```
1. Which version of eos are you running 2.0 or dawn 3?
