### ISSUE TITLE
newaccount for dawn3, so strange?!

### ISSUE THREAD

**Issue by zshchou** [EOSIO/eosjs#38]
## issue
yesterday, i had solved newaccount's error on my imac with the help of chris-allnutt. @chris-allnutt
today, in my macbookpro, newaccount can't run correctly.
i try to repull the code and rebuild:
```bash
git clone https://github.com/eosio/eos --recursive
cd eos
./eosio_build.sh
cd build && sudo make install
```
i use the same file(config.ini&genesis.json) with my imac.
but the result is incorrect on my macbookpro.

## code
```javascript
let testNewAccount = async () => {
  let initaPrivate = "5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3";
  let initaPublic = "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV";
  let keyProvider = initaPrivate;
  let eos = Eos.Localnet({ keyProvider });
  try {
    let res = await eos.newaccount({
      creator: "eosio",
      name: "mynewacct",
      owner: initaPublic,
      active: initaPublic,
      recovery: "eosio",
      deposit: "1 EOS"
    }, { broadcast: true });
    console.log("res", res);
    return res;
  } catch (err) {
    console.log("err", err);
    return err;
  }
};
```
## result

```json
api error => http://127.0.0.1:8888/v1/chain/push_transaction {"compression":"none","data":{"expiration":"2018-03-27T05:26:09","region":0,"ref_block_num":491,"ref_block_prefix":1476926362,"packed_bandwidth_words":23,"context_free_cpu_bandwidth":0,"context_free_actions":[],"actions":[{"account":"eosio","name":"newaccount","authorization":[{"actor":"eosio","permission":"active"}],"data":"0000000000ea30550000c80819aea6970100000000010002c0ded2bc1f1305fb0faac5e6c03ee3a1924234985427b6167ca569d13df435cf01000100000000010002c0ded2bc1f1305fb0faac5e6c03ee3a1924234985427b6167ca569d13df435cf010001000000010000000000ea305500000000a8ed3232010000"}]},"signatures":["EOSK7E7u5Q484VDzZiFqSGTF6xB6DB8mzss3nu66FgQkRwFxAbxgbF3nWg2JrhHfuPEXXh5f17JByQahJ4zpMJqrkwEHYiSvJ"]} { Error: {"code":500,"message":"InternalService Error","error":{"code":10,"name":"assert_exception","message":"Assert Exception","details":"w < count(): ","stack_trace":[{"level":"error","file":"static_variant.hpp","line":344,"method":"set_which","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":327,"method":"operator()","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":568,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":327,"method":"operator()","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":568,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":327,"method":"operator()","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":568,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":327,"method":"operator()","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":568,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":614,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"}]}}
    at /Users/zshchou/Projects/inkeos/node_modules/eosjs-api/lib/apigen.js:98:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7) status: 500, statusText: 'Internal Server Error' }
```
```json
{ Error: {"code":500,"message":"Internal Service Error","error":{"code":10,"name":"assert_exception","message":"Assert Exception","details":"w < count(): ","stack_trace":[{"level":"error","file":"static_variant.hpp","line":344,"method":"set_which","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":327,"method":"operator()","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":568,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":327,"method":"operator()","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":568,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":327,"method":"operator()","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":568,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":327,"method":"operator()","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":568,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":614,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"}]}}
    at /Users/zshchou/Projects/inkeos/node_modules/eosjs-api/lib/apigen.js:98:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7) status: 500, statusText: 'Internal Server Error' }
[push_transaction error] '{"code":500,"message":"Internal Service Error","error":{"code":10,"name":"assert_exception","message":"Assert Exception","details":"w < count(): ","stack_trace":[{"level":"error","file":"static_variant.hpp","line":344,"method":"set_which","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":327,"method":"operator()","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":568,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":327,"method":"operator()","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":568,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":327,"method":"operator()","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":568,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":327,"method":"operator()","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":568,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":614,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"}]}}', transaction 'f1d5b95a0000eb019a1b08581700000000010000000000ea305500409e9a2264b89a010000000000ea305500000000a8ed32327c0000000000ea30550000c80819aea6970100000000010002c0ded2bc1f1305fb0faac5e6c03ee3a1924234985427b6167ca569d13df435cf01000100000000010002c0ded2bc1f1305fb0faac5e6c03ee3a1924234985427b6167ca569d13df435cf010001000000010000000000ea305500000000a8ed3232010000'
{"code":500,"message":"Internal Service Error","error":{"code":10,"name":"assert_exception","message":"Assert Exception","details":"w < count(): ","stack_trace":[{"level":"error","file":"static_variant.hpp","line":344,"method":"set_which","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":327,"method":"operator()","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":568,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":327,"method":"operator()","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":568,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":327,"method":"operator()","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":568,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":327,"method":"operator()","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":568,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"},{"level":"warn","file":"raw.hpp","line":614,"method":"unpack","hostname":"","thread_name":"thread-0","timestamp":"2018-03-27T05:25:09.743"}]}}
```

**Comment by zshchou** [comment]
I repull and rebuild on ubuntu 16.04, it's OK.
why?!

**Comment by jcalfee** [comment]
Make sure your using eosjs from the dawn3 branch.  If you change branches you have to run `npm i` again each time.

This ticket may help you, I made a fix in eos.js yesterday.. It is checked in to the dawn3 branch now.
https://github.com/EOSIO/eosjs/issues/37

**Comment by zshchou** [comment]
my project is the same one, eosjs for dawn3.

**Comment by jcalfee** [comment]
did you review #37?

**Comment by zshchou** [comment]
my project's package.json:
    "babel-polyfill": "^6.26.0",
    "eosjs": "^7.0.2",

**Comment by jcalfee** [comment]
I see .. I ported the fix in #37 to dawn3 .. please try v7.1.2  ..

**Comment by jcalfee** [comment]
Related: https://github.com/EOSIO/eosjs/commit/dfdd7413a9eebb812d6679bebf20fad5db1033af

**Comment by jcalfee** [comment]
The real cause was not 37, but that your eosjs and eos node versions are not compatible..  Dawn3 is not release so you'll have to stay up to date or freeze the version of the eos node.  Try docker/up.sh, if that works and you understand a little docker I think this could make it much easier to stay up to date on the pre-release features..

**Comment by zshchou** [comment]
update eosjs to 7.1.2, all is ok. thx
