### ISSUE TITLE
Node-Fetch not found

### ISSUE THREAD

**Issue by betdiceone** [EOSIO/eosjs#394]
This error is coming up when the latest beta version is used:
```
Error: Cannot find module 'node-fetch' 
```

I've tried `npm install node-fetch`. But, another error was shown:
```
(node:2687) UnhandledPromiseRejectionWarning: Error: Invalid cast from type 'object_type' to string
    at new RpcError (/root/kkkk/node_modules/eosjs/dist/eosjs-rpcerror.js:22:28)
    at JsonRpc.<anonymous> (/root/kkkk/node_modules/eosjs/dist/eosjs-jsonrpc.js:117:35)
    at step (/root/kkkk/node_modules/eosjs/dist/eosjs-jsonrpc.js:35:23)
    at Object.next (/root/kkkk/node_modules/eosjs/dist/eosjs-jsonrpc.js:16:53)
    at fulfilled (/root/kkkk/node_modules/eosjs/dist/eosjs-jsonrpc.js:7:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2687) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2687) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any ideas?

I am running on Ubuntu 18.04. I've test it in Windows 10, it works fine.

**Comment by jeffreyssmith2nd** [comment]
Can you show some more code around what you're doing?

I tested sending a basic transaction on Ubuntu 18.04 using Node 8.12 and didn't see this error.

**Comment by betdiceone** [comment]
only installed the package and tried to required the package..

```
const eosjs = require('eosjs');
const fetch = require('node-fetch');                            // node only; not needed in browsers
const { TextDecoder, TextEncoder } = require('text-encoding');  // node, IE11 and IE Edge Browsers
```

That's all.

**Comment by naoyeye** [comment]
@betdiceone  your Node version?
