### ISSUE TITLE
Helloworld contract - ReferenceError: headers is not defined

### ISSUE THREAD

**Issue by Joelone** [EOSIO/eosjs#44]
When I use "7aefccc 6.1.11" of eosjs with hello world smart contract, there is an error as following:

> initialised helloworld
(node:20693) UnhandledPromiseRejectionWarning: ReferenceError: headers is not defined
    at transactionHeaders (/home/joel/eosjs/app/hello.js:13:29)
    at transaction (/home/joel/eosjs/src/write-api.js:416:5)
    at Object.transaction (/home/joel/eosjs/src/write-api.js:147:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:20693) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by Joelone** [comment]
Here is source code of hello.js
```
Eos = require('../src')
const binaryen = require('binaryen')
const fs = require('fs')

// Optional configuration..
config = {
  keyProvider: ['5KQwr......'], // WIF string or array of keys..
  httpEndpoint: 'http://127.0.0.1:8888',
  mockTransactions: () => 'pass', // or 'fail'
  transactionHeaders: (expireInSeconds, callback) => {
    callback(null/*error*/, headers)
  },
  expireInSeconds: 60,
  broadcast: true,
  debug: false,
  sign: true
}

eos = Eos.Localnet(config, binaryen)

contractDir = `contracts`
wast = fs.readFileSync(`${contractDir}/hello/hello.wast`)
abi = fs.readFileSync(`${contractDir}/hello/hello.abi`)

// Publish contract to the blockchain
eos.setcode('helloworld', 0, 0, wast, abi)

const options = {
  broadcast: true,
  sign: true,
  scope: [ "helloworld" ],
  authorization: [{
      "account": "helloworld",
      "permission": "active"
    } ]
}
eos.contract('helloworld', options)
  .then((helloworld) => {
    console.log(helloworld)
    console.log("initialised helloworld")
})

//eosc push message helloworld sayhello '{"sayto":"inita"}' -S helloworld
try {
  eos.transaction({
    scope: ['helloworld'],
    messages: [{
      code: 'helloworld',
      type: 'sayhello',
      authorization: [{
        "account": "helloworld",
        "permission": "active"
      }],
      data: {
        "sayto": "inita"
      },
    }]
  })
} catch(e) {
  console.error(e)
}

```

**Comment by Joelone** [comment]
I guess I may miss some config in transactionHeaders. Any hints?
Thanks!

**Comment by jcalfee** [comment]
Delete everything in config that you don't absolutely need.

**Comment by jcalfee** [comment]
Same with options .. eosjs is designed to have defaults for all that..

**Comment by Joelone** [comment]
Thanks jcalfee, I got different error after removed some items in config and options

```
Eos = require('../src')
const binaryen = require('binaryen')
const fs = require('fs')

// Optional configuration..
config = {
  keyProvider: ['5KQwrPb...'], // WIF string or array of keys..
  httpEndpoint: 'http://127.0.0.1:8888',
}

eos = Eos.Localnet(config)

contractDir = `contracts`
wast = fs.readFileSync(`${contractDir}/hello/hello.wast`)
abi = fs.readFileSync(`${contractDir}/hello/hello.abi`)

// Publish contract to the blockchain
eos.setcode('helloworld', 0, 0, wast, abi)

const options = {
}
console.log("before eos.contract")
eos.contract('helloworld',options)
  .then((helloworld) => {
    // console.log(helloworld)
    console.log("initialised helloworld")
})

console.log("before eos.transaction")
try {
  eos.transaction({
    scope: ['helloworld'],
    messages: [{
      code: 'helloworld',
      type: 'sayhello',
      authorization: [{
        "account": "helloworld",
        "permission": "active"
      }],
      data: {
        "sayto": "inita"
      }
    }]
  })
} catch(e) {
  console.error(e)
}
```

**Comment by Joelone** [comment]
Here is the new message with cleaner version of config and options:

```
before eos.contract
before eos.transaction
initialised helloworld
{ AssertionError [ERR_ASSERTION]: required: config.binaryen = require("binaryen") setcode.code message.data transaction.messages
    at setcode.code.fromObject (/home/joel/eosjs/src/structs.js:275:5)
    at Object.fromObject (/home/joel/eosjs/node_modules/fcbuffer/lib/struct.js:141:15)
    at message.data.fromObject (/home/joel/eosjs/src/structs.js:333:27)
    at Object.fromObject (/home/joel/eosjs/node_modules/fcbuffer/lib/struct.js:141:15)
    at Object.fromObject (/home/joel/eosjs/node_modules/fcbuffer/lib/types.js:320:28)
    at Object.fromObject (/home/joel/eosjs/node_modules/fcbuffer/lib/struct.js:144:34)
    at rawTx (/home/joel/eosjs/src/write-api.js:434:36)
    at /home/joel/eosjs/src/write-api.js:573:5
    at /home/joel/eosjs/node_modules/eosjs-api/lib/exported-helpers.js:65:7
    at /home/joel/eosjs/node_modules/eosjs-api/lib/exported-helpers.js:75:7
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
{ Error: {"code":400,"message":"Bad Request","details":"irrelevant authority included (3030003)\nMessage declared authorities it did not need: [{\"account\":\"helloworld\",\"permission\":\"active\"}]\n\n\n\n"}
    at /home/joel/eosjs/node_modules/eosjs-api/lib/apigen.js:98:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) status: 400, statusText: 'Bad Request' }
[push_transaction error] '{"code":400,"message":"Bad Request","details":"irrelevant authority included (3030003)\nMessage declared authorities it did not need: [{\"account\":\"helloworld\",\"permission\":\"active\"}]\n\n\n\n"}', digest '45c0db7828eb8eecc25a0100408a97721aa36a000100408a97721aa36a0000003446d5bcc10100408a97721aa36a00000000a8ed323208000000000093dd74'
{"code":400,"message":"Bad Request","details":"irrelevant authority included (3030003)\nMessage declared authorities it did not need: [{\"account\":\"helloworld\",\"permission\":\"active\"}]\n\n\n\n"}
(node:5959) UnhandledPromiseRejectionWarning: {"code":400,"message":"Bad Request","details":"irrelevant authority included (3030003)\nMessage declared authorities it did not need: [{\"account\":\"helloworld\",\"permission\":\"active\"}]\n\n\n\n"}
(node:5959) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5959) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by Joelone** [comment]
According to the error message, "irrelevant authority included", I remove the authority from message and modify the last part of code as:

```
try {
  eos.transaction({
    scope: ['helloworld'],
    messages: [{
      code: 'helloworld',
      type: 'sayhello',
      data: {
        "sayto": "inita"
      }
    }]
  })
} catch(e) {
  console.error(e)
}
```

**Comment by Joelone** [comment]
Then it said "Expecting message.authorization array".

```
before eos.contract
before eos.transaction
initialised helloworld
(node:6923) UnhandledPromiseRejectionWarning: TypeError: Expecting message.authorization array
    at arg.messages.forEach.message (/home/joel/eosjs/src/write-api.js:404:15)
    at Array.forEach (<anonymous>)
    at transaction (/home/joel/eosjs/src/write-api.js:402:18)
    at Object.transaction (/home/joel/eosjs/src/write-api.js:147:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:6923) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6923) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ AssertionError [ERR_ASSERTION]: required: config.binaryen = require("binaryen") setcode.code message.data transaction.messages
    at setcode.code.fromObject (/home/joel/eosjs/src/structs.js:275:5)
    at Object.fromObject (/home/joel/eosjs/node_modules/fcbuffer/lib/struct.js:141:15)
    at message.data.fromObject (/home/joel/eosjs/src/structs.js:333:27)
    at Object.fromObject (/home/joel/eosjs/node_modules/fcbuffer/lib/struct.js:141:15)
    at Object.fromObject (/home/joel/eosjs/node_modules/fcbuffer/lib/types.js:320:28)
    at Object.fromObject (/home/joel/eosjs/node_modules/fcbuffer/lib/struct.js:144:34)
    at rawTx (/home/joel/eosjs/src/write-api.js:434:36)
    at /home/joel/eosjs/src/write-api.js:573:5
    at /home/joel/eosjs/node_modules/eosjs-api/lib/exported-helpers.js:65:7
    at /home/joel/eosjs/node_modules/eosjs-api/lib/exported-helpers.js:75:7
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

**Comment by jcalfee** [comment]
Because your deploying a contract you need this:
```js
config.binaryen = require("binaryen")
Eos.Localnet(config)
```

**Comment by Joelone** [comment]
Thank you very much, the code is much cleaner now.

```
Eos = require('../src')
const fs = require('fs')

// Optional configuration..
config = {
  keyProvider: ['5KQwrPb...'], // WIF string or array of keys..
  httpEndpoint: 'http://127.0.0.1:8888',
}

config.binaryen = require("binaryen")
eos = Eos.Localnet(config)

contractDir = `contracts`
wast = fs.readFileSync(`${contractDir}/hello/hello.wast`)
abi = fs.readFileSync(`${contractDir}/hello/hello.abi`)

// Publish contract to the blockchain
eos.setcode('helloworld', 0, 0, wast, abi)

//eosc push message helloworld sayhello '{"sayto":"inita"}' -S helloworld
eos.contract('helloworld', helloworld => { // or .then(
    helloworld.sayhello('inita')
})

```

**Comment by Joelone** [comment]
I feel like I'm very close to make it work. From the last line of message,it looks like the ```sayhello``` be called before the contract be set.
```
(node:21847) UnhandledPromiseRejectionWarning: TypeError: helloworld.sayhello is not a function
    at eos.contract.helloworld (/home/joel/eosjs/app/hello.js:33:16)
    at callback (/home/joel/eosjs/node_modules/eosjs-api/lib/process-args.js:68:9)
    at writeApi.genContractActions.then.catch.r (/home/joel/eosjs/src/write-api.js:60:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:21847) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21847) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Assembling WASM...

```

**Comment by jcalfee** [comment]
sayhello needs to be in the actions section of your ABI..

**Comment by Joelone** [comment]
It is in actions section of hello.abi, and I verify it with command line work.
```
{
  "types": [],
  "structs": [{
      "name": "hello",
      "base": "",
      "fields": {
        "from": "account_name",
        "to": "account_name"
      }
    }
  ],
  "actions": [{
      "action_name": "sayhello",
      "type": "hello"
    }
  ],
  "tables": [{
      "table_name": "hello",
      "index_type": "i64",
      "key_names": [
        "from"
      ],
      "key_types": [
        "account_name"
      ],
      "type": "hello"
    }
  ]
}
```

**Comment by jcalfee** [comment]
Fyi: `action_name` is for dawn2 but that is renamed to `name` in dawn3..

This was a problem here quite involved so there could still be an issue, I didn't have actions implemented until version 6.1.4: https://github.com/EOSIO/eosjs/issues/18 .. Looks like your using 6.1.11 though..

Can you tell me what this prints: `console.log(Object.keys(helloworld))`

**Comment by jcalfee** [comment]
I don't have this docker environment in dawn2 .. 

Can you try this as a work-around?  Rename your action or the struct so it has the same name like this:
```js
  "actions": [{
      "action_name": "transfer",
      "type": "transfer"
}
```

**Comment by Joelone** [comment]
Rename the action/table are all good until I push message action to it. I guess the keyword transfer is reserve for EOS system. 

```
$ ./eosc push message helloworld tansfer '{"from":"helloworld","to":"inita"}' -S helloworld,inita
267194ms            main.cpp:1128                 operator()           ] Converting argument to binary...
267204ms            main.cpp:1195                 main                 ] Failed with error: Assert Exception (10)
status_code == 200: Error code 500
: {"code":500,"message":"Internal Service Error","details":"7 bad_cast_exception: Bad Cast\nInvalid cast from object_type to string\n    {\"type\":\"object_type\"}\n      variant.cpp:476 as_string\n\n    {\"code\":\"helloworld\",\"type\":\"tansfer\",\"obj\":{\"from\":\"helloworld\",\"to\":\"inita\"}}\n      chain_controller.cpp:1566 message_to_binary"}

```

**Comment by Joelone** [comment]
The smart contract code are compiled with tag DAWN-2018-02-14 on EOS.
Here is the eosc command line result. If you think the previous error is caused by older EOS, I'm going to move a more recent version of EOS.
```
$ eosc push message helloworld sayhello '{"sayto":"inita"}' -S helloworld
1062248ms            main.cpp:1128                 operator()           ] Converting argument to binary...
{
  "transaction_id": "c816f67cba4c7b7d75bc2c6b67ace22013d0ee05b1ed4dcbcd000eb93f744501",
  "processed": {
    "ref_block_num": 873,
    "ref_block_prefix": 4256484897,
    "expiration": "2018-04-04T20:18:11",
    "scope": [
      "helloworld"
    ],
    "signatures": [],
    "messages": [{
        "code": "helloworld",
        "type": "sayhello",
        "authorization": [],
        "data": {
          "sayto": "inita"
        },
        "hex_data": "000000000093dd74"
      }
    ],
    "output": [{
        "notify": [],
        "deferred_trxs": []
      }
    ]
  }
}
```

**Comment by jcalfee** [comment]
Right now you can use `npm i eosjs@dawn3` with `Eos.Localnet(..)` and if you have docker, run go.sh in `./docker`  [master]branch .. you'll see a function in go.sh that you can use for the Eos command-line interface.  Use that to deploy your smart contract in dawn3 ..

**Comment by jcalfee** [comment]
`console.log(Object.keys(helloworld))` needs to be the first line in the callback

In your "Rename" comment, I'm not sure why this involves a transfer.  Looks like you figured it out later though.

**Comment by Joelone** [comment]
I can't make "rename to transfer" work, then I revert back the original action name "sayhello".
I changed the order of call
```
eos.contract('helloworld', helloworld => { // or .then(
    console.log(Object.keys(helloworld))
    helloworld.sayhello('inita')
})
```

The keys in object seems to be empty. Beside the keyProvider in config, are there other place I need to put the keys?

```
[]
(node:31863) UnhandledPromiseRejectionWarning: TypeError: helloworld.sayhello is not a function

```

**Comment by jcalfee** [comment]
no .. you should probably try with dawn3 .. I should have another round of updates by tomorrow..

**Comment by Joelone** [comment]
Got it, it's better to spend time on dawn3. I close this issue now.
Thank you very much!

**Comment by jcalfee** [comment]
Instead of eos.contract try eos.transaction .. 
```js
eos.transaction('helloworld', helloworld => {
})
```

**Comment by jcalfee** [comment]
I know why.. The contract method is sending the error object first.. You need a plcae hodler:
```js
eos.contract('currency', (error, currency)=>{
})
```

**Comment by Joelone** [comment]
With the change with error object, the code looks like:

```
eos.contract('helloworld', (error, helloworld) => { // or .then(
    console.log(Object.keys(helloworld))
    helloworld.sayhello('inita')
})
```
The message become:
```
(node:28008) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at eos.contract (/home/joel/eosjs/app/hello.js:24:24)
    at callback (/home/joel/eosjs/node_modules/eosjs-api/lib/process-args.js:68:9)
    at writeApi.genContractActions.then.catch.r (/home/joel/eosjs/src/write-api.js:58:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:28008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ AssertionError [ERR_ASSERTION]: required: config.binaryen = require("binaryen") setcode.code action.data transaction.actions
    at setcode.code.fromObject (/home/joel/eosjs/src/structs.js:391:5)
    at Object.fromObject (/home/joel/eosjs/node_modules/fcbuffer/lib/struct.js:148:15)
    at action.data.fromObject (/home/joel/eosjs/src/structs.js:449:27)
    at Object.fromObject (/home/joel/eosjs/node_modules/fcbuffer/lib/struct.js:148:15)
    at Object.fromObject (/home/joel/eosjs/node_modules/fcbuffer/lib/types.js:373:28)
    at Object.fromObject (/home/joel/eosjs/node_modules/fcbuffer/lib/struct.js:151:34)
    at rawTx (/home/joel/eosjs/src/write-api.js:394:36)
    at /home/joel/eosjs/src/write-api.js:569:5
    at /home/joel/eosjs/node_modules/eosjs-api/lib/exported-helpers.js:68:7
    at /home/joel/eosjs/node_modules/eosjs-api/lib/exported-helpers.js:78:7
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

**Comment by Joelone** [comment]
If I use **transaction** in place of **contract** 
```
eos.transaction('helloworld', helloworld => { // or .then(
    console.log(Object.keys(helloworld))
    helloworld.sayhello('inita')
})
```
The output message is
```
(node:28184) UnhandledPromiseRejectionWarning: TypeError: e.fields is not iterable
    at abi.structs.forEach.e (/home/joel/eosjs/src/abi-cache.js:59:28)
    at Array.forEach (<anonymous>)
    at abiToFcSchema (/home/joel/eosjs/src/abi-cache.js:57:17)
    at network.getCode.then (/home/joel/eosjs/src/abi-cache.js:23:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:28184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ AssertionError [ERR_ASSERTION]: required: config.binaryen = require("binaryen") setcode.code action.data transaction.actions
    at setcode.code.fromObject (/home/joel/eosjs/src/structs.js:391:5)
    at Object.fromObject (/home/joel/eosjs/node_modules/fcbuffer/lib/struct.js:148:15)
    at action.data.fromObject (/home/joel/eosjs/src/structs.js:449:27)
    at Object.fromObject (/home/joel/eosjs/node_modules/fcbuffer/lib/struct.js:148:15)
    at Object.fromObject (/home/joel/eosjs/node_modules/fcbuffer/lib/types.js:373:28)
    at Object.fromObject (/home/joel/eosjs/node_modules/fcbuffer/lib/struct.js:151:34)
    at rawTx (/home/joel/eosjs/src/write-api.js:394:36)
    at /home/joel/eosjs/src/write-api.js:569:5
    at /home/joel/eosjs/node_modules/eosjs-api/lib/exported-helpers.js:68:7
    at /home/joel/eosjs/node_modules/eosjs-api/lib/exported-helpers.js:78:7
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }

```
