### ISSUE TITLE
Error: Expected string containing name

### ISSUE THREAD

**Issue by lachlangreenbank** [EOSIO/eosjs#522]
related to #455 #429 

**Version of EOSJS**
eosjs20.0.0beta3

**Describe the bug**
I'm trying to make a contract action with Node.js and i get this error message.

The contract is the eosio.token contract.

The error says i'm missing the 'name' param but it is clearly there. People have had this issue before but all issues have been closed and gone radio silent.

```
Error: Expected string containing name
    at SerialBuffer.pushName (C:\Users\LACHLAN\Desktop\smartpressWeb\ContractGenerator\node_modules\eosjs\dist\eosjs-serialize.js:234:19)
    at Object.serialize (C:\Users\LACHLAN\Desktop\smartpressWeb\ContractGenerator\node_modules\eosjs\dist\eosjs-serialize.js:814:57)
    at Object.serializeStruct [as serialize] (C:\Users\LACHLAN\Desktop\smartpressWeb\ContractGenerator\node_modules\eosjs\dist\eosjs-serialize.js:564:28)
    at serializeActionData (C:\Users\LACHLAN\Desktop\smartpressWeb\ContractGenerator\node_modules\eosjs\dist\eosjs-serialize.js:1041:12)
    at Object.serializeAction (C:\Users\LACHLAN\Desktop\smartpressWeb\ContractGenerator\node_modules\eosjs\dist\eosjs-serialize.js:1051:15)
    at Api.<anonymous> (C:\Users\LACHLAN\Desktop\smartpressWeb\ContractGenerator\node_modules\eosjs\dist\eosjs-api.js:277:71)
    at step (C:\Users\LACHLAN\Desktop\smartpressWeb\ContractGenerator\node_modules\eosjs\dist\eosjs-api.js:44:23)
    at Object.next (C:\Users\LACHLAN\Desktop\smartpressWeb\ContractGenerator\node_modules\eosjs\dist\eosjs-api.js:25:53)
    at fulfilled (C:\Users\LACHLAN\Desktop\smartpressWeb\ContractGenerator\node_modules\eosjs\dist\eosjs-api.js:16:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

```
```

async function tx() {
    try {
      let resp = await api.transact({ actions: [{
          account: paramss.contract,
          name: 'transfer',
          authorization: [{
            actor: paramss.sender,
            permission: 'active',
          }],
          data: {
            from: paramss.sender,
            to: paramss.receiver,
            quantity: `${(paramss.amount).toFixed(4)} ${paramss.symbol}`,
            memo: paramss.memo,
          },
        }]
      }, {
        blocksBehind: 3,
        expireSeconds: 30,
      });
      resp = {...resp, paramss}
      console.log(resp);
        return resp
      } catch(err) {
        console.log(err)
        return err
    }
  }
  tx()

```
**To Reproduce**
1. try to run this action on the specified version of eosjs

**Expected behavior**
Transaction goes through

**Desktop (please complete the following information):**
 - OS: Windows10

**Additional context**
I'm using the eosio.token contract.

**Comment by tbfleming** [comment]
This report exhibits a common reason it goes silent: the actual value passed to api.transact isn't shown. e.g. maybe paramss.sender is null, or is a number, or is an object.

**Comment by lachlangreenbank** [comment]
I tested it with a hard coded string value with the same result.

**Comment by lachlangreenbank** [comment]
I had tried hard coding nearly everything.

Turns out the sender value became undefined in my object.

For anyone with this issue, try first hard coding the entire transaction and seeing if the error still occurs.
