### ISSUE TITLE
TypeError: f is not a function - Error when calling transact() for creating new EOS account

### ISSUE THREAD

**Issue by tkeidar** [EOSIO/eosjs#541]
**Version of EOSJS**
20.0.0 (tried also on 20.0.0-beta3 and got the same error)

**Describe the bug**
I'm trying to create an account by the code below and fails on calling transact() with "TypeError: f is not a function" exception.

```javascript
  const rpc = new JsonRpc('http://dev.cryptolions.io:38888'); // I tried with few different rpc endpoints
  const signatureProvider = new JsSignatureProvider([privateKey]);

  const api = new Api({
    rpc,
    signatureProvider,
    textDecoder: new TextDecoder(),
    textEncoder: new TextEncoder(),
  });

  const result = await api.transact(
    {
      actions: [
        {
          account: 'eosio',
          name: 'newaccount',
          authorization: [
            {
              actor: parentAccountName,
              permission: 'active',
            },
          ],
          data: {
            creator: parentAccountName,
            newact: accountName,
            owner: {
              threshold: 1,
              keys: [
                {
                  key: publicKey,
                  weight: 1,
                },
              ],
              accounts: [],
              waits: [],
            },
            active: {
              threshold: 1,
              keys: [
                {
                  key: accountName,
                  weight: 1,
                },
              ],
              accounts: [],
              waits: [],
            },
          },
        },
        {
          account: 'eosio',
          name: 'buyrambytes',
          authorization: [
            {
              actor: parentAccountName,
              permission: 'active',
            },
          ],
          data: {
            payer: parentAccountName,
            receiver: accountName,
            bytes: 8192,
          },
        },
        {
          account: 'eosio',
          name: 'delegatebw',
          authorization: [
            {
              actor: parentAccountName,
              permission: 'active',
            },
          ],
          data: {
            from: parentAccountName,
            receiver: accountName,
            stake_net_quantity: '1.0000 EOS',
            stake_cpu_quantity: '1.0000 EOS',
            transfer: false,
          },
        },
      ],
    },
    {
      blocksBehind: 3,
      expireSeconds: 30,
    },
  );
```

Here is the full error message:
```TypeError: f is not a function
at JsonRpc.<anonymous> (.../node_modules/eosjs/src/eosjs-jsonrpc.ts:47:30)
at step (.../node_modules/eosjs/dist/eosjs-jsonrpc.js:36:23)
at Object.next (.../node_modules/eosjs/dist/eosjs-jsonrpc.js:17:53)
at .../node_modules/eosjs/dist/eosjs-jsonrpc.js:11:71
at new Promise (<anonymous>)
at __awaiter (.../node_modules/eosjs/dist/eosjs-jsonrpc.js:7:12)
at JsonRpc.fetch (.../node_modules/eosjs/dist/eosjs-jsonrpc.js:92:16)
at JsonRpc.<anonymous> (.../node_modules/eosjs/src/eosjs-jsonrpc.ts:102:27)
at step (.../node_modules/eosjs/dist/eosjs-jsonrpc.js:36:23)
at Object.next (.../node_modules/eosjs/dist/eosjs-jsonrpc.js:17:53)
at .../node_modules/eosjs/dist/eosjs-jsonrpc.js:11:71
at new Promise (<anonymous>)
at __awaiter (.../node_modules/eosjs/dist/eosjs-jsonrpc.js:7:12)
at JsonRpc.get_info (.../node_modules/eosjs/dist/eosjs-jsonrpc.js:205:16)
at Api.<anonymous> (.../node_modules/eosjs/src/eosjs-api.ts:219:35)
at step (.../node_modules/eosjs/dist/eosjs-api.js:47:23)
at Object.next (.../node_modules/eosjs/dist/eosjs-api.js:28:53)
at .../node_modules/eosjs/dist/eosjs-api.js:22:71
at new Promise (<anonymous>)
at __awaiter (.../node_modules/eosjs/dist/eosjs-api.js:18:12)
at Api.transact (.../node_modules/eosjs/dist/eosjs-api.js:345:16)
at .../src/wallet/wallet.controller.ts:82:28
at Generator.next (<anonymous>)
at .../src/wallet/wallet.controller.ts:7:71
at new Promise (<anonymous>)
at __awaiter (.../src/wallet/wallet.controller.ts:3:12)
at createEosAccount (.../src/wallet/wallet.controller.ts:86:12)
at asyncUtilWrap (.../node_modules/express-async-handler/index.js:3:20)
at Layer.handle [as handle_request] (.../node_modules/express/lib/router/layer.js:95:5)
at next (.../node_modules/express/lib/router/route.js:137:13)
at loggerMiddleware (.../src/logger/logger.middleware.ts:14:5)
at Layer.handle [as handle_request] (.../node_modules/express/lib/router/layer.js:95:5)
at next (.../node_modules/express/lib/router/route.js:137:13)
at Guard._middleware (.../node_modules/express-jwt-permissions/index.js:76:7)

**Comment by tkeidar** [comment]
`const rpc = new JsonRpc('http://dev.cryptolions.io:38888');
  const signatureProvider = new JsSignatureProvider([privateKey]);

  const api = new Api({
    rpc,
    signatureProvider,
    textDecoder: new TextDecoder(),
    textEncoder: new TextEncoder(),
  });

  const result = await api.transact(
    {
      actions: [
        {
          account: 'eosio',
          name: 'newaccount',
          authorization: [
            {
              actor: parentAccountName,
              permission: 'active',
            },
          ],
          data: {
            creator: parentAccountName,
            newact: accountName,
            owner: {
              threshold: 1,
              keys: [
                {
                  key: publicKey,
                  weight: 1,
                },
              ],
              accounts: [],
              waits: [],
            },
            active: {
              threshold: 1,
              keys: [
                {
                  key: accountName,
                  weight: 1,
                },
              ],
              accounts: [],
              waits: [],
            },
          },
        },
        {
          account: 'eosio',
          name: 'buyrambytes',
          authorization: [
            {
              actor: parentAccountName,
              permission: 'active',
            },
          ],
          data: {
            payer: parentAccountName,
            receiver: accountName,
            bytes: 8192,
          },
        },
        {
          account: 'eosio',
          name: 'delegatebw',
          authorization: [
            {
              actor: parentAccountName,
              permission: 'active',
            },
          ],
          data: {
            from: parentAccountName,
            receiver: accountName,
            stake_net_quantity: '1.0000 EOS',
            stake_cpu_quantity: '1.0000 EOS',
            transfer: false,
          },
        },
      ],
    },
    {
      blocksBehind: 3,
      expireSeconds: 30,
    },
  );`

**Comment by tkeidar** [comment]
Found the

**Comment by krtk6160** [comment]
I'm getting this error in spite of initializing `rpc` with `fetch`

This is my code:

`const rpc = new JsonRpc('http://jungle2.cryptolions.io:80', { fetch });
rpc.get_block(1).then(console.log);
`

This is my error:
`
(node:16931) UnhandledPromiseRejectionWarning: TypeError: f is not a function
    at JsonRpc.<anonymous> (/home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:99:46)
    at step (/home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:36:23)
    at Object.next (/home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:17:53)
    at /home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:11:71
    at new Promise (<anonymous>)
    at __awaiter (/home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:7:12)
    at JsonRpc.fetch (/home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:92:16)
    at JsonRpc.<anonymous> (/home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:163:55)
    at step (/home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:36:23)
    at Object.next (/home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:17:53)
(node:16931) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:16931) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by krtk6160** [comment]
@tkeidar Were you able to fix it?

**Comment by tkeidar** [comment]
@krtk6160 what apparently solved it for me was the missing node-fetch when initiating new JsonRpc

**Comment by krtk6160** [comment]
@tkeidar I initially tried importing node-fetch as `const {fetch} = require('fetch')` and the rpc object was failing. 
Using `const fetch = require('fetch')` instead fixed it.

**Comment by BhaskarDutta2209** [comment]
> I'm getting this error in spite of initializing `rpc` with `fetch`. eosjs version is `20.0.0`
> 
> This is my code:
> 
> ```
> const rpc = new JsonRpc('http://jungle2.cryptolions.io:80', { fetch });
> rpc.get_block(1).then(console.log);
> ```
> 
> This is my error:
> 
> ```
> (node:16931) UnhandledPromiseRejectionWarning: TypeError: f is not a function
>     at JsonRpc.<anonymous> (/home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:99:46)
>     at step (/home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:36:23)
>     at Object.next (/home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:17:53)
>     at /home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:11:71
>     at new Promise (<anonymous>)
>     at __awaiter (/home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:7:12)
>     at JsonRpc.fetch (/home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:92:16)
>     at JsonRpc.<anonymous> (/home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:163:55)
>     at step (/home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:36:23)
>     at Object.next (/home/krtk6160/Desktop/konnectSense/node_modules/eosjs/dist/eosjs-jsonrpc.js:17:53)
> (node:16931) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:16931) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

I am having the same error. Kindly help me out with the solution
