### ISSUE TITLE
Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by benjamintshi** [EOSIO/eosjs#574]
**Version of EOSJS**
version 20.0.0-beta2.2

**Describe the bug**
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at __values (/Users/shitao/eos/eosjs_demo/node_modules/eosjs/dist/eosjs-jssig.js:42:46)
    at new JsSignatureProvider (/Users/shitao/eos/eosjs_demo/node_modules/eosjs/dist/eosjs-jssig.js:65:38)
    at new RpcControl (/Users/shitao/eos/eosjs_demo/view/rpc.control.js:11:21)
    at Object.<anonymous> (/Users/shitao/eos/eosjs_demo/view/rpc/transfer.js:8:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)

**Comment by benjamintshi** [comment]
solve by version 20.0.0-beta2
