### ISSUE TITLE
deserializeActionData throws

### ISSUE THREAD

**Issue by robertkowalski** [EOSIO/eosjs#578]
**Version of EOSJS**
20.0.0

**Describe the bug**
`eos.Serialize.deserializeActionData()` call throws because is depends on a textDecoder instance in Serialbuffer.

**To Reproduce**
```js
const { TextEncoder, TextDecoder } = require('util')
const eos = require('eosjs')

const rpc = new JsonRpc('http://example-eos-node.example.com', { fetch })
const api = new Api({
  rpc,
  signatureProvider: keyProvider,
  textDecoder: new TextDecoder(),
  textEncoder: new TextEncoder()
})

// fetch a contract
const contract = await api.getContract('testcontract')

// call function
eos.Serialize.deserializeActionData(
  contract,
  'testcontractname',
  'testaction',
  '040000000000000040420857619DB1CA00E1F50500000000085553445400000000',
  TextEncoder,
  TextDecoder 
)
```

```
TypeError: this.textDecoder.decode is not a function
    at SerialBuffer.getSymbol (/Users/robert/bitfinex/bfx-ext-eos-multisig/node_modules/eosjs/dist/eosjs-serialize.js:352:37)
    at SerialBuffer.getAsset (/Users/robert/bitfinex/bfx-ext-eos-multisig/node_modules/eosjs/dist/eosjs-serialize.js:392:23)
    at Object.deserialize (/Users/robert/bitfinex/bfx-ext-eos-multisig/node_modules/eosjs/dist/eosjs-serialize.js:845:60)
    at Object.deserializeStruct [as deserialize] (/Users/robert/bitfinex/bfx-ext-eos-multisig/node_modules/eosjs/dist/eosjs-serialize.js:602:49)
    at Object.deserializeActionData (/Users/robert/bitfinex/bfx-ext-eos-multisig/node_modules/eosjs/dist/eosjs-serialize.js:1066:19)
    at WrkExtEosSignMultisigApi.sendTx (/Users/robert/bitfinex/bfx-ext-eos-multisig/workers/api.sign.eos.ext.wrk.js:390:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Expected behavior**
get the result of the data without exception. 

because textencoder and decoder have to get passed to the function, it should use it and not rely on the instance in `SerialBuffer`

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - node v10.16.0

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by Ivane18** [comment]
I encountered a similar problem to TextEncoder when I was running Node v10.x and solved the problem by updating node to the current version of 12.x. I am running eosjs in ubuntu 18.04 and used this article to update node. https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-18-04

**Comment by yyh1102** [comment]
have the same problem event though updating Node to 12.x

**Comment by robertkowalski** [comment]
ah, thx! makes sense!
