### ISSUE TITLE
create new account failed where active keys more then 2 

### ISSUE THREAD

**Issue by benjamintshi** [EOSIO/eosjs#583]
when i set more then two active keys ,it failed .but use two active keys is successed.

```
const result = await api.transact({
        actions: [
            {
                account: 'eosio',
                name: 'newaccount',
                authorization: [
                    {
                        actor: 'invaultmut13',
                        permission: 'owner',
                    }
                ],
                data: {
                    creator: 'invaultmut13',
                    name: 'invaultmut23',
                    owner: {
                        threshold: 1,
                        keys: [{
                            key: 'EOS5xuBTgn3jKhJzkRCpWqJHzaKtzvieUxxedCjuQsKuEFTmUy1vQ',
                            weight: 1
                        }],
                        accounts: [],
                        waits: []
                    },
                    active: {
                        threshold: 3,
                        keys: [{
                            key: 'EOS5xuBTgn3jKhJzkRCpWqJHzaKtzvieUxxedCjuQsKuEFTmUy1vQ',
                            weight: 1
                        }, {
                            key: 'EOS7LfRceX8uLuq5fjdcWQipkHUKg4CxP1JyRqCRz3VpZyXQoKVQg',
                            weight: 1
                        },{
                            key: 'EOS6W8KPPReLGkLUNmgtSjAbnAzdUnhX4oXjKMJNSTzTNztFfnBVM',
                            weight: 1
                        },{
                            key: 'EOS6n864Ww7mUKR1iaQ6YiJ5TYMFfNMdt4ujyjnBqEvXYH5r1rsWu',
                            weight: 1
                        }],
                        accounts: [],
                        waits: []
                    },
                }
            },
            {
                account: 'eosio',
                name: 'buyrambytes',
                authorization: [
                    {
                        actor: 'invaultmut13',
                        permission: 'owner',
                    }
                ],
                data: {
                    payer: 'invaultmut13',
                    receiver: 'invaultmut23',
                    bytes: 8192,
                }
            },
            // {
            //     account: 'eosio',
            //     name: 'delegatebw',
            //     authorization: [
            //         {
            //             actor: 'invaultmut13',
            //             permission: 'owner',
            //         }
            //     ],
            //     data: {
            //         from: 'invaultmut13',
            //         receiver: 'invaultmut24',
            //         stake_net_quantity: '1.0000 EOS',
            //         stake_cpu_quantity: '1.0000 EOS',
            //         transfer: false,
            //     }
            // }
        ],
    }, {
        blocksBehind: 3,
        expireSeconds: 300,
        broadcast: true
    });

```

error msg :

```
(node:18867) UnhandledPromiseRejectionWarning: Error: Invalid active authority
    at new RpcError (/Users/shitao/eos/eosjs_demo/node_modules/eosjs/dist/eosjs-rpcerror.js:23:28)
    at JsonRpc.<anonymous> (/Users/shitao/eos/eosjs_demo/node_modules/eosjs/dist/eosjs-jsonrpc.js:118:35)
    at step (/Users/shitao/eos/eosjs_demo/node_modules/eosjs/dist/eosjs-jsonrpc.js:36:23)
    at Object.next (/Users/shitao/eos/eosjs_demo/node_modules/eosjs/dist/eosjs-jsonrpc.js:17:53)
    at fulfilled (/Users/shitao/eos/eosjs_demo/node_modules/eosjs/dist/eosjs-jsonrpc.js:8:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:18867) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18867) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by benjamintshi** [comment]
this pro is solved.

**Comment by benjamintshi** [comment]
active keys need sort .
0: "EOS5xuBTgn3jKhJzkRCpWqJHzaKtzvieUxxedCjuQsKuEFTmUy1vQ"
1: "EOS7LfRceX8uLuq5fjdcWQipkHUKg4CxP1JyRqCRz3VpZyXQoKVQg"
2: "EOS6W8KPPReLGkLUNmgtSjAbnAzdUnhX4oXjKMJNSTzTNztFfnBVM"
3: "EOS6n864Ww7mUKR1iaQ6YiJ5TYMFfNMdt4ujyjnBqEvXYH5r1rsWu"
after sort can success.
0: "EOS5xuBTgn3jKhJzkRCpWqJHzaKtzvieUxxedCjuQsKuEFTmUy1vQ"
1: "EOS6W8KPPReLGkLUNmgtSjAbnAzdUnhX4oXjKMJNSTzTNztFfnBVM"
2: "EOS6n864Ww7mUKR1iaQ6YiJ5TYMFfNMdt4ujyjnBqEvXYH5r1rsWu"
3: "EOS7LfRceX8uLuq5fjdcWQipkHUKg4CxP1JyRqCRz3VpZyXQoKVQg"
