### ISSUE TITLE
Exception when exec contract action

### ISSUE THREAD

**Issue by shrimpliu** [EOSIO/eosjs#60]
After I deployed the `eosio.bios` contract, I try to execute `setpriv` action.
```
eos.contract('eosio').then(function (contract) {
    contract.setpriv('eosio', 1, { authorization: 'eosio' });
});
```
Then jump out of the exception:
```
TypeError: Expecting hex string or buffer in action.data action.data = {"account":"eosio","is_priv":1} transaction.actions = [{"account":"eosio","name":"setpriv","authorization":[{"actor":"eosio","permission":"active"}],"data":{"account":"eosio","is_priv":1}}]
    at actionDataAppendByteBuffer (/Users/shrimp/work/eos-boot-sim/node_modules/eosjs/lib/structs.js:535:17)
    at Object.appendByteBuffer (/Users/shrimp/work/eos-boot-sim/node_modules/fcbuffer/lib/struct.js:108:15)
    at Object.appendByteBuffer (/Users/shrimp/work/eos-boot-sim/node_modules/fcbuffer/lib/types.js:350:16)
    at Object.appendByteBuffer (/Users/shrimp/work/eos-boot-sim/node_modules/fcbuffer/lib/struct.js:110:20)
    at toByteBuffer (/Users/shrimp/work/eos-boot-sim/node_modules/fcbuffer/lib/fcbuffer.js:284:8)
    at Function.toBuffer (/Users/shrimp/work/eos-boot-sim/node_modules/fcbuffer/lib/fcbuffer.js:271:22)
    at /Users/shrimp/work/eos-boot-sim/node_modules/eosjs/lib/write-api.js:611:26
    at /Users/shrimp/work/eos-boot-sim/node_modules/eosjs/lib/write-api.js:766:7
    at /Users/shrimp/work/eos-boot-sim/node_modules/eosjs-api/lib/exported-helpers.js:69:7
    at /Users/shrimp/work/eos-boot-sim/node_modules/eosjs-api/lib/exported-helpers.js:79:7
```
Error is located here in file `eosjs/lib/structs.js`:
```
 var data = typeof object.data === 'string' ? new Buffer(object.data, 'hex') : object.data;
        if (!Buffer.isBuffer(data)) {
          throw new TypeError('Expecting hex string or buffer in action.data');
        }
```
Do you have any documentation or insight that could help?

**Comment by rise-worlds** [comment]
yes, plase give examples details of action

**Comment by jcalfee** [comment]
I deployed under an account called `eosio.bios` ..
```js
eos.contract('eosio.bios', (err, c)=>eosio.bios=c)
osio.bios.setpriv('eosio', 1, { authorization: 'eosio.bios' });
```
Then got this error:
"eosio.bios does not have permission to call this API"

Using eosjs 8.0.1 ..

have to run, be back soon..

**Comment by jcalfee** [comment]
>"eosio.bios does not have permission to call this API"

This could be a back-end issue.. Kevin is talking to Anton about this..
