### ISSUE TITLE
No Map Support

### ISSUE THREAD

**Issue by Trevor-Ultra** [EOSIO/eosjs#613]
**Version of EOSJS**
20.0.0

**Describe the bug**
Currently smart contracts that utilize `std::map<uint64_t, uint64_t>` or any map pairing in particular do not currently have support in `eosjs`.

**To Reproduce**
In `cleos` we can perform an action where a smart contract uses a map and no issues arise.
Example: `cleos push action somecontract test '["username",[[0,1]], "Update"]' -p somecontract`

This action will perform flawlessly in `cleos`.
Now when we do the same thing inside of `eosjs`

```
api.transact(
    {
        actions: [
            {
                account: 'somecontract',
                name: 'test',
                authorization: [
                    {
                        actor: 'somecontract',
                        permission: 'active'
                    }
                ],
                data: {
                    owner: 'username',
                    amap: [[0,1]],
                    memo: 'Update'
                }
            }
        ]
    },
    { broadcast: true, blocksBehind: 1, expireSeconds: 60 }
)
    .then(res => {
        console.log(res);
    })
    .catch(err => {
        console.error(err);
    });
```

The follow error should be produced:
```
Error: missing pair_uint64_uint64.key (type=uint64)
    at Object.serializeStruct [as serialize] (/node_modules/eosjs/dist/eosjs-serialize.js:571:27)
    at Object.serializeArray [as serialize] (/node_modules/eosjs/dist/eosjs-serialize.js:640:26)
    at Object.serializeStruct [as serialize] (/node_modules/eosjs/dist/eosjs-serialize.js:564:28)
    at serializeActionData (/node_modules/eosjs/dist/eosjs-serialize.js:1041:12)
    at Object.serializeAction (/node_modules/eosjs/dist/eosjs-serialize.js:1051:15)
    at Api.<anonymous> (/node_modules/eosjs/dist/eosjs-api.js:278:71)
    at step (/node_modules/eosjs/dist/eosjs-api.js:47:23)
    at Object.next (/node_modules/eosjs/dist/eosjs-api.js:28:53)
    at fulfilled (/node_modules/eosjs/dist/eosjs-api.js:19:58)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Expected behavior**
Serialize an Array of Array's acting as a map.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Browser: Brave

**Comment by Trevor-Ultra** [comment]
This is someone who had a similar issue with maps: #550

**Comment by Trevor-Ultra** [comment]
Here's an example of an `.abi` output for a map.

```
{
            "name": "pair_uint64_asset",
            "base": "",
            "fields": [
                {
                    "name": "key",
                    "type": "uint64"
                },
                {
                    "name": "value",
                    "type": "asset"
                }
            ]
        },
```

**Comment by tbfleming** [comment]
eosjs doesn't support cleos's object-as-array shortcut. Use this: `[{"key": 0, "value": 1}]`

**Comment by Trevor-Ultra** [comment]
> eosjs doesn't support cleos's object-as-array shortcut. Use this: `[{"key": 0, "value": 1}]`

No luck with this either.

**Comment by tbfleming** [comment]
Did the error change?

**Comment by tbfleming** [comment]
Also, show the abi section for the `test` action.

**Comment by Trevor-Ultra** [comment]
> Did the error change?

Error changed to `invalid number`. Console logged it down and it's trying to pass the now object as a number.

> Also, show the abi section for the test action.
Here's a similar abi to what we're working with as far as actions go.

```
{
            "name": "test",
            "base": "",
            "fields": [
                {
                    "name": "testa",
                    "type": "name"
                },
                {
                    "name": "testb",
                    "type": "uint32"
                },
                {
                    "name": "testc",
                    "type": "uint32"
                },
                {
                    "name": "teste",
                    "type": "uint64?"
                },
                {
                    "name": "testf",
                    "type": "bool"
                },
                {
                    "name": "testg",
                    "type": "uint64?"
                },
                {
                    "name": "testh",
                    "type": "name?"
                },
                {
                    "name": "testi",
                    "type": "name?"
                },
                {
                    "name": "testj",
                    "type": "name?"
                },
                {
                    "name": "testk",
                    "type": "uint64?"
                },
                {
                    "name": "testl",
                    "type": "uint8[]"
                },
                {
                    "name": "testm",
                    "type": "uint128?"
                },
                {
                    "name": "testn",
                    "type": "pair_uint64_asset[]"
                },
                {
                    "name": "testo",
                    "type": "bool"
                },
                {
                    "name": "testp",
                    "type": "pair_name_uint64[]"
                },
                {
                    "name": "testq",
                    "type": "time_point_sec?"
                },
                {
                    "name": "testr",
                    "type": "time_point_sec?"
                },
                {
                    "name": "tests",
                    "type": "pair_uint64_asset[]"
                },
                {
                    "name": "testt",
                    "type": "uint64?"
                }
            ]
        },
```

**Comment by Trevor-Ultra** [comment]
Issue was that the version I was using was **v20.0.0** and not **v20.0.2.** The NPM package is not up to date.
